### PR TITLE
"Active" interpolation (Cubic only)

### PR DESCRIPTION
**Pull request by KCErb**
Hi there, thanks for the great library!

In my use case, it is more efficient (about 7x faster specifically) to directly compute the polynomials of the points I want to interpolate since I know those points ahead of time. So this is a shot at me changing the interpolator I need today (cubic) from passively returning a function to actively calculating the known "query" points.

In this draft, I've named the method `cubicSplineInterpolate` to indicate an `active` voice rather than passive.

I have this running in my project now and figured I may as well submit a PR in case you're interested. No hard feelings if it doesn't fit in with what you're wanting to do here :)

Cheers

### CODE REVIEW

**Comment by chdh** [comment]
Thanks for your PR. I will move the computation of the coefficients to a separate function `computeCubicPolyCoefficients` as in your PR and export that function and `createPolynomialFunction`. Then you can write your optimized version outside of the package.
I'm not sure whether I should also export `Arrays_binarySearch`.

**Comment by KCErb** [comment]
Sounds good!

I'd be fine if you didn't export it. I noticed that the output is a little idiosyncratic (I have to do a -i-2 in my case to the result if it's negative, but it seems some of the other functions modified the output in other ways) so if you didn't provide it I'd just copy and paste yours and then add the little `-i-2` dance directly into the function body. :)

**Comment by chdh** [comment]
I have reworked the entire module. Could you have a look at it?

**Comment by KCErb** [comment]
Thanks, I pulled it down and worked it into my app with no trouble. Thank you!

**Pull request closed without merging**
